# Generated by Django 5.2.4 on 2025-07-06 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time when the transaction occurred', verbose_name='transaction date'),
        ),
    ]
